package nl.adg.qwixx.e2e;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import nl.adg.qwixx.e2e.utils.BaseIntegrationTest;
import nl.adg.qwixx.e2e.utils.CatalogPageCapture;
import nl.adg.qwixx.e2e.utils.SheetVariantCatalog;
import nl.adg.qwixx.e2e.utils.SheetVariantCatalog.Variant;
import nl.adg.qwixx.e2e.utils.TestUtils;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.openqa.selenium.WebDriver;

/**
 * Docs generator (not a normal test): renders the /mini-catalog page against the real Spring-served
 * SPA and writes docs/MINI_SHEETS.md — the player-list thumbnail of every sheet variant, pristine
 * and half-played. The thumbnail is otherwise only reachable by starting a real multi-player game,
 * so a rendering bug in a rarely-picked variant is easy to miss; this page is where you eyeball them
 * all at once. It stays out of the README, which documents the full sheets.
 *
 * <p>Guarded by the same system property as {@link OptionPreviewGeneratorIT}; both run from
 * scripts/generate-option-docs.sh.
 */
@EnabledIfSystemProperty(named = "generate.option.previews", matches = "true")
class MiniSheetPreviewGeneratorIT extends BaseIntegrationTest {

    private static final Path REPO_ROOT =
            Path.of(System.getProperty("user.dir")).resolve("..").normalize();
    private static final Path IMG_DIR = REPO_ROOT.resolve("docs/mini-sheet-previews");
    private static final Path DOC = REPO_ROOT.resolve("docs/MINI_SHEETS.md");
    // Image links are relative to the doc, which sits beside the image directory.
    private static final String IMG_REL = "mini-sheet-previews";

    @Test
    void generateMiniSheetDocs() throws Exception {
        List<Variant> variants = SheetVariantCatalog.variants();
        WebDriver driver = TestUtils.createDriver();
        try {
            CatalogPageCapture.capture(driver, "/mini-catalog", variants.stream().map(Variant::key).toList(), IMG_DIR);
        } finally {
            driver.quit();
        }
        Files.writeString(DOC, markdown(variants), StandardCharsets.UTF_8);
    }

    private String markdown(List<Variant> variants) {
        StringBuilder md = new StringBuilder();
        md.append("# Mini sheets\n\n");
        md.append("<!-- Auto-generated by MiniSheetPreviewGeneratorIT (server e2e). Do not edit by hand;\n");
        md.append("     run `./scripts/generate-option-docs.sh` to refresh — the pre-push hook regenerates\n");
        md.append("     and blocks the push if these are stale. -->\n\n");
        md.append("The thumbnail the player list draws for every *other* player's sheet, per variant. ");
        md.append("Left is pristine; right has every other cell crossed, every lock crossed and the last ");
        md.append("lockable row closed, so each variant's crossed states are visible side by side.\n\n");
        md.append("The full sheets these are thumbnails of are in the [README](../README.md#game-options). ");
        md.append("Browse them live at `/mini-catalog`.\n\n");

        int number = 1;
        for (Variant variant : variants) {
            md.append("### ").append(number).append(". ").append(variant.label()).append("\n\n");
            if (!variant.description().isEmpty()) md.append(variant.description()).append("\n\n");
            md.append("![").append(variant.label()).append("](")
                    .append(IMG_REL).append('/').append(variant.key()).append(".png)\n\n");
            number++;
        }
        return md.toString();
    }
}
