package nl.adg.qwixx.e2e;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import nl.adg.qwixx.e2e.utils.BaseIntegrationTest;
import nl.adg.qwixx.e2e.utils.CatalogPageCapture;
import nl.adg.qwixx.e2e.utils.SheetVariantCatalog;
import nl.adg.qwixx.e2e.utils.SheetVariantCatalog.Variant;
import nl.adg.qwixx.e2e.utils.TestUtils;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.openqa.selenium.WebDriver;

/**
 * Docs generator (not a normal test): renders the /option-catalog page against the real
 * Spring-served SPA, screenshots each option's sheet preview into docs/option-previews/, and
 * rewrites the auto-generated game-options block in the repo README. Because it renders the live
 * components, the images always track the current styling.
 *
 * <p>Guarded by a system property so the regular {@code verify} run never triggers it. Run with:
 * {@code ./mvnw failsafe:integration-test failsafe:verify -Dit.test=OptionPreviewGeneratorIT
 * -Dgenerate.option.previews=true} (see scripts/generate-option-docs.sh).
 */
@EnabledIfSystemProperty(named = "generate.option.previews", matches = "true")
class OptionPreviewGeneratorIT extends BaseIntegrationTest {

    private static final Path REPO_ROOT =
            Path.of(System.getProperty("user.dir")).resolve("..").normalize();
    private static final Path IMG_DIR = REPO_ROOT.resolve("docs/option-previews");
    private static final Path README = REPO_ROOT.resolve("README.md");
    private static final String IMG_REL = "docs/option-previews";
    private static final String START_MARKER = "<!-- OPTIONS:START -->";
    private static final String END_MARKER = "<!-- OPTIONS:END -->";

    @Test
    void generateOptionDocs() throws Exception {
        List<Variant> variants = SheetVariantCatalog.variants();
        WebDriver driver = TestUtils.createDriver();
        try {
            CatalogPageCapture.capture(driver, "/option-catalog", variants.stream().map(Variant::key).toList(), IMG_DIR);
        } finally {
            driver.quit();
        }
        rewriteReadme(variants);
    }

    private void rewriteReadme(List<Variant> variants) throws Exception {
        StringBuilder md = new StringBuilder();
        md.append(START_MARKER).append('\n');
        md.append("<!-- Auto-generated by OptionPreviewGeneratorIT (server e2e). Do not edit between these markers;\n");
        md.append("     run `./scripts/generate-option-docs.sh` to refresh — the pre-push hook regenerates\n");
        md.append("     and blocks the push if these are stale. -->\n\n");

        int number = 1;
        for (Variant variant : variants) {
            md.append("### ").append(number).append(". ").append(variant.label()).append("\n\n");
            if (!variant.description().isEmpty()) md.append(variant.description()).append("\n\n");
            md.append("![").append(variant.label()).append("](")
                    .append(IMG_REL).append('/').append(variant.key()).append(".png)\n\n");
            number++;
        }

        md.append(END_MARKER);

        String readme = Files.readString(README, StandardCharsets.UTF_8);
        int start = readme.indexOf(START_MARKER);
        int end = readme.indexOf(END_MARKER);
        if (start < 0 || end < 0) {
            throw new IllegalStateException("README is missing the OPTIONS markers");
        }
        String updated = readme.substring(0, start) + md + readme.substring(end + END_MARKER.length());
        Files.writeString(README, updated, StandardCharsets.UTF_8);
    }
}
