package nl.adg.qwixx.e2e;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.List;
import nl.adg.qwixx.e2e.utils.BaseIntegrationTest;
import nl.adg.qwixx.e2e.utils.SpringAppTestHelper;
import nl.adg.qwixx.e2e.utils.TestUtils;
import nl.adg.qwixx.game.GameOption;
import nl.adg.qwixx.game.OptionCategory;
import nl.adg.qwixx.game.QwixxGameOptions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.WebDriverWait;

/**
 * Docs generator (not a normal test): renders the /option-catalog page against the real
 * Spring-served SPA, screenshots each option's sheet preview into docs/option-previews/, and
 * rewrites the auto-generated game-options block in the repo README. Because it renders the live
 * components, the images always track the current styling.
 *
 * <p>Guarded by a system property so the regular {@code verify} run never triggers it. Run with:
 * {@code ./mvnw failsafe:integration-test failsafe:verify -Dit.test=OptionPreviewGeneratorIT
 * -Dgenerate.option.previews=true} (see scripts/generate-option-docs.sh).
 */
@EnabledIfSystemProperty(named = "generate.option.previews", matches = "true")
class OptionPreviewGeneratorIT extends BaseIntegrationTest {

    private static final Path REPO_ROOT =
            Path.of(System.getProperty("user.dir")).resolve("..").normalize();
    private static final Path IMG_DIR = REPO_ROOT.resolve("docs/option-previews");
    private static final Path README = REPO_ROOT.resolve("README.md");
    private static final Path EN_JSON = REPO_ROOT.resolve("client/public/i18n/en.json");
    private static final String IMG_REL = "docs/option-previews";
    private static final String START_MARKER = "<!-- OPTIONS:START -->";
    private static final String END_MARKER = "<!-- OPTIONS:END -->";

    @Test
    void generateOptionDocs() throws Exception {
        Files.createDirectories(IMG_DIR);
        WebDriver driver = TestUtils.createDriver();
        try {
            captureScreenshots(driver);
        } finally {
            driver.quit();
        }
        rewriteReadme();
    }

    private void captureScreenshots(WebDriver driver) throws Exception {
        driver.get("http://127.0.0.1:" + SpringAppTestHelper.getPort() + "/option-catalog");
        // The page sets [data-catalog-ready] once every preview layout has loaded and rendered.
        new WebDriverWait(driver, Duration.ofSeconds(30))
                .until(d -> !d.findElements(By.cssSelector("[data-catalog-ready]")).isEmpty());

        for (GameOption option : modeOptions()) {
            WebElement shot = driver.findElement(By.cssSelector("[data-opt-key='" + option.key() + "']"));
            File png = shot.getScreenshotAs(OutputType.FILE);
            Files.copy(png.toPath(), IMG_DIR.resolve(option.key() + ".png"),
                    java.nio.file.StandardCopyOption.REPLACE_EXISTING);
        }
    }

    private void rewriteReadme() throws Exception {
        JsonNode i18n = new ObjectMapper().readTree(EN_JSON.toFile());
        StringBuilder md = new StringBuilder();
        md.append(START_MARKER).append('\n');
        md.append("<!-- Auto-generated by OptionPreviewGeneratorIT (server e2e). Do not edit between these markers;\n");
        md.append("     run `./scripts/generate-option-docs.sh` to refresh — the pre-push hook regenerates\n");
        md.append("     and blocks the push if these are stale. -->\n\n");

        // Only the sheet-changing (MODE) variants are listed — each with its live preview image.
        for (GameOption option : modeOptions()) {
            String label = resolve(i18n, option.labelKey());
            md.append("### ").append(label).append("\n\n");
            String desc = resolve(i18n, option.descriptionKey());
            if (!desc.isEmpty()) md.append(desc).append("\n\n");
            md.append("![").append(label).append("](")
                    .append(IMG_REL).append('/').append(option.key()).append(".png)\n\n");
        }

        md.append(END_MARKER);

        String readme = Files.readString(README, StandardCharsets.UTF_8);
        int start = readme.indexOf(START_MARKER);
        int end = readme.indexOf(END_MARKER);
        if (start < 0 || end < 0) {
            throw new IllegalStateException("README is missing the OPTIONS markers");
        }
        String updated = readme.substring(0, start) + md + readme.substring(end + END_MARKER.length());
        Files.writeString(README, updated, StandardCharsets.UTF_8);
    }

    /** MODE options are the ones that change the sheet, so they are the ones we screenshot. */
    private static List<GameOption> modeOptions() {
        return QwixxGameOptions.all().stream()
                .filter(o -> o.category() == OptionCategory.MODE)
                .toList();
    }

    /** Resolves a dotted i18n key (e.g. "gameOption.baseDescription") against the en.json tree. */
    private static String resolve(JsonNode root, String dottedKey) {
        JsonNode node = root;
        for (String segment : dottedKey.split("\\.")) {
            if (node == null) return "";
            node = node.get(segment);
        }
        return node != null && node.isTextual() ? node.asText() : "";
    }
}
